//usuario
export const LOGIN = "LOGIN";
export const RESET_LOGIN = "RESET_LOGIN";
export const REGISTRARSE = "REGISTRARSE";
export const GET_ALL_USUARIOS = "GET_ALL_USUARIOS";
export const GET_USUARIOS_BY_ROL = "GET_USUARIOS_BY_ROL";
export const GET_USER = "GET_USER";
export const GET_USER_BY_ID="GET_USER_BY_ID";
export const GET_USER_BY_DNI = "GET_USER_BY_DNI";
export const RESET_USER = "RESET_USER";
export const MODIFICA_USUARIO = "MODIFICA_USUARIO";
export const MODIFICA_CONTRASEÑA = "MODIFICA_CONTRASEÑA";
//Articulos
export const LOADING = "LOADING";
export const CREA_ARTICULO = "CREA_ARTICULO";
export const GET_ARTICULOS = "GET_ARTICULOS";
export const GET_ARTICULO = "GET_ARTICULO";
export const GET_ARTICULO_BY_ID = "GET_ARTICULO_BY_ID";
export const GET_ARTICULO_POR_NOMBRE = "GET_ARTICULO_POR_NOMBRE";
export const RESET_ARTICULO = "RESET_ARTICULO";
export const ELIMINA_ARTICULO = "ELIMINA_ARTICULO";
