//usuario
export const LOGIN = "LOGIN";
export const RESET_LOGIN = "RESET_LOGIN";
export const REGISTRARSE = "REGISTRARSE";
export const GET_ALL_USUARIOS = "GET_ALL_USUARIOS";
export const GET_USER = "GET_USER";
export const GET_USER_BY_ID="GET_USER_BY_ID";
export const GET_USER_BY_DNI = "GET_USER_BY_DNI";
export const RESET_USER = "RESET_USER";
export const MODIFICA_USUARIO = "MODIFICA_USUARIO";
export const MODIFICA_CONTRASEÑA = "MODIFICA_CONTRASEÑA";
//productos
export const LOADING = "LOADING";
export const GET_PRODUCTOS = "GET_PRODUCTOS";
export const GET_PRODUCTO = "GET_PRODUCTO";
export const GET_PRODUCTO_BY_ID = "GET_PRODUCTO_BY_ID";
export const GET_PRODUCTO_POR_NOMBRE = "GET_PRODUCTO_POR_NOMBRE";
export const RESET_PRODUCTO = "RESET_PRODUCTO";
export const GET_PRODUTOS_OFERTA = "GET_PRODUTOS_OFERTA";
export const GET_PRODS_RANGO_PRECIO = "GET_PRODS_RANGO_PRECIO";
export const ELIMINA_PRODUCTO = "ELIMINA_PRODUCTO";
